<?php

/**
 * @file
 * Custom code for the allershop store.
 */

/**
 * Implements hook_menu().
 */
function aller_store_menu() {
  $items['admin/commerce/overview/add/page'] = array(
    'title' => 'Add page',
    'page callback' => 'drupal_goto',
    'page arguments' => array('node/add/page'),
    'access arguments' => array('create page content'),
    'type' => MENU_LOCAL_ACTION,
    'weight' => 0,
  );
  $items['admin/commerce/overview/add/page'] = array(
    'title' => 'Add banner',
    'page callback' => 'drupal_goto',
    'page arguments' => array('node/add/banners'),
    'access arguments' => array('create banners content'),
    'type' => MENU_LOCAL_ACTION,
    'weight' => 0,
  );
  $items['admin/commerce/overview/add/produktvisning'] = array(
    'title' => 'Add new product',
    'page callback' => 'drupal_goto',
    'page arguments' => array('node/add/produktvisning'),
    'access arguments' => array('create produktvisning content'),
    'type' => MENU_LOCAL_ACTION,
    'weight' => 1,
  );
  $items['admin/commerce/overview/add/taxonomy/produkter'] = array(
    'title' => 'Add category',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/structure/taxonomy/produkter'),
    'access arguments' => array('administer taxonomy'),
    'type' => MENU_LOCAL_ACTION,
    'weight' => 2,
  );

  return $items;
}

/**
 * Implements hook_form_alter();
 * Have a date popup.
 */
function aller_store_form_alter(&$form, &$form_state, $form_id) {
  if (module_exists('date_popup') && isset($form_state['view']->name)) {
    if ($form_state['view']->name == 'c_dashboard_order_exports') {
      $form['created']['min']['#type'] = 'date_popup';
      $form['created']['min']['#date_format'] = 'Y-m-d';
      $form['created']['max']['#type'] = 'date_popup';
      $form['created']['max']['#date_format'] = 'Y-m-d';
    }
    if ($form_state['view']->name == 'c_dashboard_product_charts') {
      $form['created']['#type'] = 'date_popup';
      $form['created']['#date_format'] = 'Y-m-d';
      $form['created_1']['#type'] = 'date_popup';
      $form['created_1']['#date_format'] = 'Y-m-d';
    }
  }

  if ($form_id == 'user_profile_form') {
    $form['#pre_render'][] = 'aller_store_user_profile_form_pre_render';
  }
}

function aller_store_user_profile_form_pre_render($form) {
  // Hide language settings, except if it's super admin user.
  // Rob needs to switch to English, sometimes...
  if (isset($form['locale']) && $form['#user']->uid != 1) {
    hide($form['locale']);
  }

  // We don't need metatags for users.
  if (isset($form['metatags'])) {
    hide($form['metatags']);
  }

  return $form;
}

/**
 * Implements hook_commerce_currency_info_alter().
 *
 * Because the default display of AUD is awful
 */
function aller_store_commerce_currency_info_alter(&$currencies, $langcode) {
  $currencies['NOK']['symbol'] = 'kr';
  $currencies['NOK']['symbol_placement'] = 'after';
  $currencies['NOK']['code_placement'] = '';
}

/**
 * Implements hook_preprocess_node().
 *
 * Show only 1 image on products teasers
 */
function aller_store_preprocess_node(&$vars) {
  if ($vars['view_mode'] == 'teaser') {
    if (isset($vars['content']['product:field_product_image'])) {
      $product_image = array($vars['content']['product:field_product_image']['#items'][0]);
      $vars['content']['product:field_product_image']['#items'] = $product_image;
    }
  }
}
